### ISSUE TITLE
Support for jsx

### ISSUE THREAD

**Issue by bernatfortet** [philsinatra/NestedCommentsVSCode#11]
Support for jsx would be awesome. Right now commenting a line in jsx and then commenting a larger block is a pain.

**Comment by philsinatra** [comment]
Tricky since there are different comment formats within a .jsx file. Can you give me an example of a scenario where the default commenting is frustrating?

**Comment by bernatfortet** [comment]
Here's a video with the case: https://streamable.com/r98aq

**Comment by philsinatra** [comment]
v2.2.2 adds basic JSX support.

![nest-react](https://user-images.githubusercontent.com/1465808/48639208-eae95700-e9a0-11e8-8e02-ced12398d730.gif)

**Comment by bernatfortet** [comment]
That's amazing! 
I just updated but it doesn't seem to work for me. Do I have to do something special?

**Comment by philsinatra** [comment]
You shouldn't have to. Just reload VSCode after the update and it should work as expected. If not, open up an issue and send me some details about what's happening for you.
