### ISSUE TITLE
Move nested comment reversal to new keyboard shortcut

### ISSUE THREAD

**Issue by eheu** [philsinatra/NestedCommentsVSCode#14]
It would be nice to have the Nest Comments extension give a keyboard shortcut for reversing the nested comments. 

I use CTRL+K CTRL+C for commenting and CTRL+K CTRL+U for uncommenting.

Let's say you have a block of code such as this:
```
<body>
    <p></p>
</body>
```
If you comment out the p element (CTRL+K CTRL+C) ...
```
<body>
    <!-- <p></p> -->
</body>
```
... and comment out the entire block of code (CTRL+K CTRL+C) ...
```
<!-- <body>
    <!~~ <p></p> ~~>
</body> -->
```
... and uncomment the entire block of code (CTRL+K CTRL+U) ...
```
<body>
    <!~~ <p></p> ~~>
</body>
```
... you are left with the invalid safe character comment!

**Comment by philsinatra** [comment]
The default functionality is to detect whether the highlighted text begins with a comment or not, which determines whether it comments or uncomments.

What you're describing doesn't seem to be working correctly. In the following image I'm using the default keyboard shortcut (<kbd>CMD</kbd> + <kbd>OPTION</kbd> + <kbd>/</kbd>) to run the nest comments command each time.

![nested-comments](https://user-images.githubusercontent.com/1465808/51990994-26f86800-2478-11e9-88c5-16369b55c0a9.gif)

If you highlight your code the same way and execute the command, whether through a shortcut or the command palette, does it work similarly?

**Comment by eheu** [comment]
> If you highlight your code the same way and execute the command, whether through a shortcut or the command palette, does it work similarly?

Indeed. But the issue I've opened is a feature request for moving the uncomment functionality to a different keyboard shortcut.

That way it suits the workflow of using one shortcut for commenting, and another for uncommenting.

**Comment by philsinatra** [comment]
Okay I understand what you're saying now. I appreciate the thought but I don't plan on making a change like this because I think it is actually more cumbersome to have to remember two shortcuts. Having a single command handle the toggle is less muscle memory. This extension has over 34K installations across three different text editors and I haven't had a request to change the key bindings before so I'm not inclined to make a change to how it currently works.

**Comment by eheu** [comment]
Alright, thanks for giving it your consideration.
