### ISSUE TITLE
Color Theme

### ISSUE THREAD

**Issue by Astrantia** [philsinatra/NestedCommentsVSCode#16]
@philsinatra Thanks for the extension! This should not be an issue, so I'm sorry.
I wanted to ask you a quention about the color theme used here https://github.com/philsinatra/NestedCommentsVSCode/blob/master/images/nest-html.gif
Do you still use it or remember which one it was?

**Comment by philsinatra** [comment]
It's called Popping and Locking Black. Here's the link: https://marketplace.visualstudio.com/items?itemName=philsinatra.popping-and-locking-vscode-black
