### ISSUE TITLE
Html comments not working

### ISSUE THREAD

**Issue by cjpgaspar** [philsinatra/NestedCommentsVSCode#17]
With the update 2.3.0 HTML nested comments stop working

**Comment by philsinatra** [comment]
Can you be more specific as to what is not working? Version 2.3 has been live since February and has not had any issues to this point.

**Comment by cjpgaspar** [comment]
After a few tries I narrowed it to when I already have a line comment.
For instance, in this case:

```
<!-- <span></span> -->
<span></span>
<!-- <span></span -->
```

When I try to comment line 2 and 3 this happens:

```
<!-- <span></span> -->-->
<span></span>
<!-- <span></span 
```

Or in this:
```
<!-- <span></span> -->
<span></span>
<!-- <span></span -->
<span></span>
```
When I try to comment line 2, 3 and 4 nothing happens

**Comment by philsinatra** [comment]
I think the problem is you're mixing cases. The nesting detects whether the code needs to be commented, or uncommented. 

```html
<!-- <span></span> -->
<span></span>
<!-- <span></span> -->
```

In this scenario, you would simply comment out the middle line, not try to nest comments for all three lines. If you expand your selection, then nesting comments makes sense. For example:

```html
<body>
  <!-- <span></span> -->
  <span></span>
  <!-- <span></span> -->
  <span></span>
</body>
```

Use the extension to nest comments on the `body` element and it will work as expected.

**Comment by cjpgaspar** [comment]
I don't know if I am doing anything wrong, but with the tag body if i try to comment line 3 to 5 it still doesn't do anything. If I use the previous version 2.2.6 it works just fine.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16052771/58333078-91248680-7e34-11e9-80b7-ab863d86ca35.gif)

**Comment by philsinatra** [comment]
Update 2.3.1 is available and should address this bug. I tested your `<span>` example specifically. Let me know if this update clears the issue for you.

**Comment by cjpgaspar** [comment]
It works great! Thank you so much
