### ISSUE TITLE
blade support

### ISSUE THREAD

**Issue by ctf0** [philsinatra/NestedCommentsVSCode#18]
is that possible ?

the comments in blade are `{{-- ... --}}`

**Comment by philsinatra** [comment]
Can you provide an example? I'm not extremely familiar with Laravel Blade. Using the HTML comment syntax outside of the Blade declaration would not work I assume?

**Comment by ctf0** [comment]
the html comment works in blade but the issue with that it will also show in the DOM.

however with blade comment, it means that this part wont be rendered, 
so maybe what we could do is simply change the already commented part using ex.`~` 
```
// before
{{-- ... --}}

// after
{{~ ... ~}}
```

and continu like any other language

**Comment by philsinatra** [comment]
Is this extension applicable though because the goal here is to handle nested comments. Can you show me a code example where nesting would be applicable?

**Comment by ctf0** [comment]
sure, lets say you have something like
```
<img class="image is--circle is-128x128"
    src="{{ $user->avatar }}"
    alt="{{ $user->name }} avatar">
<div class="container m-t-15">
    {{-- <h3 class="title">{{ $user->name }}</h3> --}}
    {{-- <div class="content">{!! $user->bio !!}</div> --}}
</div>
```

now we want to comment the whole thing, so currently this is what you would get
```
{{-- <img class="image is--circle is-128x128"
    src="{{ $user->avatar }}"
    alt="{{ $user->name }} avatar">
<div class="container m-t-15">
    {{-- <h3 class="title">{{ $user->name }}</h3> --}}
    {{-- <div class="content">{!! $user->bio !!}</div> --}}
</div> --}}
```
the last `</div> --}}` wont be respected because the commenting will stop at the first `--}}` blade encounters which is `</h3> --}}` but if we converted all the comment blocks to something like `~` then we get
```
{{-- <img class="image is--circle is-128x128"
    src="{{ $user->avatar }}"
    alt="{{ $user->name }} avatar">
<div class="container m-t-15">
    {{~ <h3 class="title">{{ $user->name }}</h3> ~}}
    {{~ <div class="content">{!! $user->bio !!}</div> ~}}
</div> --}}
```
which is the correct format

**Comment by philsinatra** [comment]
I'll take a look.
