### ISSUE TITLE
Vue comments styles and scripts

### ISSUE THREAD

**Issue by usernamehw** [philsinatra/NestedCommentsVSCode#2]
Vue file consists (in a basic form) of html, css, javascript. Currently it triggers html-like comments for all of them:

```vue
<template>
    <div id="app"></div>
</template>

<style>
body {
    color: white;
}
</style>
<script>
let foo = 1;
</script>
```
```vue
<template>
    <!-- <div id="app"></div> -->
</template>

<style>
<!-- body {
    color: white;
} -->
</style>
<script>
<!-- let foo = 1; -->
</script>
```

**Comment by philsinatra** [comment]
This is interesting. I personally don't use Vue.js. I received a request to include it from another developer, I believe under the assumption they would use the default commenting functionality in all cases unless dealing specifically with HTML and the need to next pre-existing comments.
