### ISSUE TITLE
actually it's not working in .vue file(template)

### ISSUE THREAD

**Issue by ly525** [philsinatra/NestedCommentsVSCode#20]
![image](https://user-images.githubusercontent.com/12668546/77133367-cd993100-6a9d-11ea-9802-f0b92b14b9c8.png)

can you please help me solved it ?

```vue
<v-card>
<!-- some comments -->
</v-card>

```

**Comment by philsinatra** [comment]
Based on the picture, your selection will not trigger the nesting function.

Watch the gifs on the repo homepage and focus on the selections being made. Your selection has to include existing comments, or begin/end with the comment characters.

https://github.com/philsinatra/NestedCommentsVSCode

**Comment by ly525** [comment]
OK thanks，I will read watch the gifs later
