### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by igor041** [philsinatra/NestedCommentsVSCode#21]
No working properly for me - I use VSC with HTML files. I'll open a HTML file with existing comments, select All, then hit (Alt-Ctrl-/) and instead of commenting everything, it UN-comments the existing comments. This is not what i expected or what's shown in demo - the expectation was to comment everything and rewrite the old comment syntax. Then (while it's all still selected) if i hit the combo again, it will now comment everything, but my old comments have lost the comment brackets. So when i need to uncomment everything again, my old comments are now broken..?

**Comment by philsinatra** [comment]
Do you have the same experience if you activate the plugin using the command palette?
