### ISSUE TITLE
support for Salesforce Visualforce .page file format

### ISSUE THREAD

**Issue by adam-sunpro** [philsinatra/NestedCommentsVSCode#29]
Hi,  Could you add support for Salesforce Visualforce  .page file format please?   When i try to use 'Nested Comments' program it says "file format not supported".    commenting style for Visualforce file format is like this '\'.   Thank you!

**Comment by philsinatra** [comment]
The `.page` extension can be used for files other than those written in Visualforce. I have to consider a way around this, maybe a preference where you would be able to add `.page` to your config so your VSCode recognizes that file format?

**Comment by ghost** [comment]
Hello Friend ;
is it possible to add the tpl plugin ? 
thank you for your work

**Comment by philsinatra** [comment]
@TheMedicus What is the preferred format for comments in a `.tpl` document? I'm not familiar with the syntax, and there seem to be various formats discussed online.

**Comment by ghost** [comment]
@philsinatra dear friend ;
https://prnt.sc/1xe72yp sample code system datalife engine html java php

**Comment by philsinatra** [comment]
The correct syntax is:

```tpl
{* THIS IS A COMMENT *}
```

Correct?

**Comment by ghost** [comment]
yes html java and this code

**Comment by philsinatra** [comment]
I've added support for `.tpl` files. Version 2.3.2.

**Comment by ghost** [comment]
I am really sad Friend; :((
File format not supported! I get an error 

there is a sample at this link :  >>>  https://www58.zippyshare.com/v/y89TZpxe/file.html

**Comment by philsinatra** [comment]
Your sample link was flagged as a virus threat. 👎🏼

**Comment by ghost** [comment]
I checked 3 times, there is no virus in the file

https://www66.zippyshare.com/v/zWkakvHQ/file.html

https://uploadrar.com/clotcx5tyb0v

https://www.virustotal.com/gui/file/56f4a79550a034331334afe3fcb80bb28d30be02a2af98923d7a0a4847d606db/detection

**Comment by philsinatra** [comment]
Can you open a new issue for this request and provide a code sample on Github showing the markup for a `.tpl` file?
