### ISSUE TITLE
All not html-languages now cannot be commented?

### ISSUE THREAD

**Issue by usernamehw** [philsinatra/NestedCommentsVSCode#3]
When trying to comment something out, for instance, `json` you get an error: **File format not supported**. 

This is not how this works, not at all. In vscode you can define in which languages your extension works, and, if the condition is not met, then it will use the default:

```json
{
    "key": "ctrl+/",
    "command": "extension.nestComments",
    "when": "editorTextFocus && editorHasSelection && editorLangId == 'html'"
},
{
    "key": "ctrl+/",
    "command": "extension.nestComments",
    "when": "editorTextFocus && editorHasSelection && editorLangId == 'svg'"
}
///...
```
This will trigger command only when text is selected and when language is either `html` or `svg`. If language not matches, then it will use the default comment command.

**Comment by philsinatra** [comment]
The formats this extension works in is specified:

- asp
- cfm
- htm
- html
- md
- njk
- php
- svg
- vue
- xml

This is not meant to replace the default commenting functionality (<kbd>CMD</kbd>+<kbd>/</kbd>), but rather to supplement it.
