### ISSUE TITLE
Commenting issues when selecting lines in different ways

### ISSUE THREAD

**Issue by bijink** [philsinatra/NestedCommentsVSCode#31]
1.  Nested commenting is working nicely when the starting of selection is exactly from the beginning tip of the code block. 
But, when any white-space is included at the beginning point of the selection (before the code starts), the comment gets messed.
The nested commenting is repeated by commenting the selected block again and again with new comment tags.

video.1 :
https://user-images.githubusercontent.com/79900465/140316364-d1b6e1d1-7456-4f08-8492-0968104ebe4e.mp4

2.  Comment not working when the selection starts from an already commented line.
This also removes the existing comments inside the block.

video.2:
https://user-images.githubusercontent.com/79900465/140316393-b2eab6a7-5df6-417a-ac6a-3d0242878a0e.mp4

**Comment by philsinatra** [comment]
> Nested commenting is working nicely when the starting of selection is exactly from the beginning tip of the code block.
But, when any white-space is included at the beginning point of the selection (before the code starts), the comment gets messed. The nested commenting is repeated by commenting the selected block again and again with new comment tags.

This is expected and is exactly how the extension is intended to work. While this might not match your preference, there is no bug with how the extension is currently functioning.

> Comment not working when the selection starts from an already commented line. This also removes the existing comments inside the block.

The video link to demonstrate whatever you're trying to explain is not working. Can you fix or provide details another way?

**Comment by bijink** [comment]
> This is expected and is exactly how the extension is intended to work. While this might not match your preference, there is no bug with how the extension is currently functioning.

Okey. But I suggest you to include all these suggestions in a feature update for improvement.
Thank you.

> The video link to demonstrate whatever you're trying to explain is not working. Can you fix or provide details another way?

Sorry for the video uploaded previously. Here is the gif demonstration. Please check it :

1.
![01](https://user-images.githubusercontent.com/79900465/140470071-f01de9fb-55eb-45a7-a936-2374fc50d194.gif)

2. 
![02](https://user-images.githubusercontent.com/79900465/140470106-4a93c463-3129-49ac-975b-9f2d4db33c63.gif)

**Comment by philsinatra** [comment]
Thanks for the images. Both of your comments are related to the selection area. The extension is working as expected based on the current configuration. I've made notes on your suggestions and will definitely consider these upgrades in the next release. 👍🏼 Thank you for taking the time to provide these suggestions.
