### ISSUE TITLE
Commenting creates invalid HTML unless selection is made very carefully

### ISSUE THREAD

**Issue by phoenixeliot** [philsinatra/NestedCommentsVSCode#32]
Say I have this HTML:
```html
  <div class="some classes">
    some stuff
    some stuff
  </div>
  ```
If I start my selection before the word "class=", and hold shift and move the cursor down 3 lines (to just before the last `>`), then activate this extension, I would expect this output:
```html
  <!-- <div class="some classes">
    some stuff
    some stuff
  </div> -->
```
But instead I get this output:
```html
  <div <!-- class="some classes">
    some stuff
    some stuff
  </div -->
  ```
  
<img width="217" alt="Screen Shot 2022-01-17 at 21 19 52" src="https://user-images.githubusercontent.com/491376/149859545-1dbcd4c2-7be2-4856-bafb-196c93069f32.png">

This is incorrect in several ways. Instead, the extension should comment out the entire lines instead of just the selected portion of those lines.

If you want to retain the ability to comment inline segments, perhaps you could add a second command that has the comment-by-lines behavior instead. As it is now, I just can't use this since it's much more finicky than the default comment shortcut.

**Comment by philsinatra** [comment]
Hey Phoenix, this extension is configured to toggle the comment symbols based on the cursor's location. It will not try to expand a selection. This is intentional so that users have complete control of the placement of the comment tags, which provides more flexibility in scenarios of different preferred formatting.
