### ISSUE TITLE
Support for .svelte files

### ISSUE THREAD

**Issue by cycle4passion** [philsinatra/NestedCommentsVSCode#35]
Much like vue, svelte files have up to 3 parts. I believe the script and html parts are handled fine by built in commenting. The style portion is what I am hoping NestedComments could handle.

<script>
 // JS or TS here
</script>

<div>
 HTML Here
</div>

<style>
  /* CSS Here */
</style>

**Comment by philsinatra** [comment]
This update is definitely on my list. Thanks for the request. I'll try to implement it as soon as possible.
