### ISSUE TITLE
Use in .razor files

### ISSUE THREAD

**Issue by lonix1** [philsinatra/NestedCommentsVSCode#37]
Does the extension only work with comment markers `<!--` and `-->`?

Because in .NET razor files (which are basically html) the markers are as above, as well as `@*` and `*@`. Is that possible with this extension?

**Comment by philsinatra** [comment]
Hi there. NestedComments supports other marker types based on file type/extension. The extension currently does not support determining the appropriate syntax based on cursor location (it's in the development plan for a future release).

I can add support for the HTML style markers, or the `@*` style, but not both.

I'm not familiar with Razor/.net. The file extension for Razor files is `.cshtml`, correct?

**Comment by lonix1** [comment]
Yes for Razor:
- the extension is either `.cshtml` or `.razor`
- the markers are `<!--` and `-->` for html as normal, or `@*` and `*@` when commenting code

If I understand your reply - a razor file can support both marker types simultaneously, but this extension can only support one marker type **per file**.

In a future release, maybe you could consider a config option per extension type? Then users could choose which they use more often and set it. I'd use `@*` and `*@` as they can be used for both markup and code. Maybe others would prefer the opposite.

Go ahead and close if it's out of scope. And thanks for this incredibly useful extension!

**Comment by philsinatra** [comment]
You are correct in your interpretation. The extension is based on file extension rather than cursor location. I've run into this problem myself with React and Svelte since more and more frameworks and libraries are using multiple languages in the same file. The change to support multiple syntaxes in the same file requires a significant rewrite that I have to make time to complete.

I can add one of the comment styles for you easily if it would be helpful. No one has requested Razor support in the past so you can have your pick of what would be most helpful.

**Comment by lonix1** [comment]
I really appreciate your comment.

I just checked my codebase. For razor (`.cshtml` and `.razor`) files, the `@*` / `*@` combo can be used to comment both markup and code, and there are some places where only it can be used, e.g. `<div class="foo" @*data="bar"*@ data="baz"></div>`. So it's the better choice, given the current design. If you sneak that in to a future release that would be terrific.

I guess to really solve this situation requires a rewrite like you said, I'm glad the issue affects other platforms too, as misery loves company. :wink:

**Comment by philsinatra** [comment]
Can you tell me the correct `doc.languageId` for `.cshtml` and `.razor` files? I don't have a proper environment to test these file extensions. You can find the value I'm looking for from the _Select Language Mode_ overlay.

![Screen Shot 2022-05-11 at 9 27 53 AM](https://user-images.githubusercontent.com/1465808/167861278-6efde707-d1d8-4316-b083-0877f2b0c3c4.png)

**Comment by lonix1** [comment]
I have two options in there:
- Razor (razor)
- ASP.NET Razor (aspnetcorerazor)

Which seems to correspond to [this](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers).

Frankly, I'm unsure.

**Comment by lonix1** [comment]
@joerobich We are trying to add aspnetcore support to a very popular vscode extension. Do you know what are the language ids for ".cshtml" and ".razor" files? Are they `razor` and `aspnetcorerazor` respectively? (The [docs](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers) are incomplete.)

If joerobich doesn't know, nobody knows! :smile: (He is the guy in charge of vscode's c# support.)

**Comment by JoeRobich** [comment]
@lonix1 So this boils down to there being barebones support for razor editing which ships with VS Code, as well as the enhanced experience that ships with the C# extension. Each language id is assigned to both file extensions.

"razor" comes from an extension that ships in-box with VS Code - https://github.com/microsoft/vscode/blob/2297ad5c546b455421e942743e117a3c7c9a873a/extensions/razor/package.json#L15-L31
"aspnetcorerazor" comes from the C# extension - https://github.com/OmniSharp/omnisharp-vscode/blob/a64910f65086d864ff82e7120e4a904db747ad1d/package.json#L3982-L3997

**Comment by philsinatra** [comment]
@lonix1 if the syntax is the same for both, I can add it for both language ids.

**Comment by lonix1** [comment]
@JoeRobich Thank you very much!

@philsinatra Yes. The syntax is identical.

**Comment by philsinatra** [comment]
I added support for the `@*` syntax you described above (not published), but I am not able to get VSCode to recognize this syntax as a comment. The only commenting syntax that seems to work with this file type is `<!--`. Can you give me an example of a file where the `@*` syntax works as a comment?

**Comment by lonix1** [comment]
That's unfortunate.

Example:
````razor
<div>foo</foo>
@*
This is commented.
*@

<span>Blah</Blah> @*Commented*@

<p class="bar" @*
Commented
*@ style="baz">
</p>

<main>
something    @*some comment *@
@*some comment*@
</main>
````

Razor comment [reference](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0#comments) (last block).

If this cannot be done, maybe I can open an issue on the vscode repo, though I'm unsure what to ask for.

**Comment by philsinatra** [comment]
I can't get VSCode to recognize the `@*` format. Only the `<!--` format appears to have an effect. I can easily add syntax support for the `<!--` format if that's helpful.

**Comment by lonix1** [comment]
Nah those are ignored by the renderer and the server code within is still executed. The trick is the `@* ... *@`. Thanks though!

Like I said above I don't know how to report this: what is the actual error? I can help put together a bug report but need some guidance. I'm sorry it wasted your time.

**Comment by philsinatra** [comment]
I don't think this will be considered an error or bug. The editor doesn't support nested comments by default. I doubt the devs will add a fix specifically for this format. I can try to force it in, but I can't properly test it, so I'm hesitant.

**Comment by lonix1** [comment]
That's unfortunate. TBH although I want to help debug, I've never made vscode extensions so I'm hesitant to give you false positives and thus introduce a bug! :)

I feel bad you wasted your time, but thank you very much for trying... I hope we can revisit this in the future. I appreciate everything the extension does right now, thanks!
