### ISSUE TITLE
Support for .ts files

### ISSUE THREAD

**Issue by leis42** [philsinatra/NestedCommentsVSCode#38]
Support for .ts files, please :(

**Comment by philsinatra** [comment]
Hi there. There is currently support for `.tsx` files. For standard `.ts` files, VSCode's default commenting functionality handles nested comments. Is there a specific scenario you're dealing with in Typescript that the default commenting functionality isn't addressing?

```typescript
// const one = 1;
// // const two = 2;
```

**Comment by leis42** [comment]
Specifically, nested block comments are an issue.
```
/* const one = 1;
/* const two = 2; */
const three = 3; */
```
In this situation, the scope is:
```
/* const one = 1;
/* const two = 2; */
```
To work, the first end of the scope should change to something, anything (like `*!/` or `~/`).
```
/* const one = 1;
/* const two = 2; *!/
const three = 3; */
```

**Comment by philsinatra** [comment]
Did you change a preference to use the multiline comment format instead of the default single-line format? I have never incorporated this extension into `.js` or `.ts` because the VSCode default commenting format is the single-line format, and it supports dealing with nested comments, so the functionality of this extension isn't needed.

**Comment by leis42** [comment]
By multiline, do you refer to:
```
/**
 * const one = 1
 * const two = 2
 */
```
This doesn't help me. I want simple block comment, something like this https://stackoverflow.com/questions/39847618/how-to-comment-out-a-block-of-code-that-already-has-multiple-line-comments

**Comment by philsinatra** [comment]
VSCode has preferences for the default commenting format. For JavaScript (and Typescript), that format is the single-line format:

```javascript
// this is a single line comment
// this is another single line comment

/*
this is a multiline comment
and this is more of the comment
*/
```

If you use the default `//` format, nesting works without the need for an extension:

```javascript
// this is a single line comment
const one = 1;
// this is another single line comment
```

becomes

```javascript
// // this is a single line comment
// const one = 1;
// // this is another single line comment
```

This will reverse back to the original text when you uncomment the block.

**Comment by leis42** [comment]
Yes, I know that, but I don't want to use nesting with `//`, but with `/* */` :D

**Comment by philsinatra** [comment]
Okay, sorry for my confusion. Unfortunately, this is not something on the roadmap for this extension at this time. I'm trying to avoid conflicts with the default comment mechanisms as much as possible.
