### ISSUE TITLE
How do I activate this?

### ISSUE THREAD

**Issue by dropToolzAdmin** [philsinatra/NestedCommentsVSCode#39]
The extension is not doing anything and I can't find the extension settings.

**Comment by philsinatra** [comment]
The default keybindings are:

- Windows: <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>/</kdb>
- macOS: <kbd>cmd</kbd>+<kbd>alt</kbd>+<kbd>/</kdb>

You can also trigger the extension through the command palette by searching for 'nest'.
