### ISSUE TITLE
safe to set as vscode default hotkey?

### ISSUE THREAD

**Issue by Hifilo** [philsinatra/NestedCommentsVSCode#45]
This extension is such a time-saver. thanks for making it!

I'm wondering if I can just set the default comment hotkey to your extension or is there a reason to have both set to exclusive hotkeys?

**Comment by philsinatra** [comment]
I don't see why changing the default keyboard shortcut would be unsafe. It's all about your preference. I used a different default shortcut to avoid creating a conflict.

**Comment by Hifilo** [comment]
> I don't see why changing the default keyboard shortcut would be unsafe. It's all about your preference. I used a different default shortcut to avoid creating a conflict.

I was wondering if there was a particular conflict you came across that made you set the keybind to something else, but you are saying you set it as a precaution. Understandable. I'll set it to the default for now. If I notice anything odd I'll set it back.

Cheers
