### ISSUE TITLE
Does not recognize CSS embedded in HTML, causing syntax errors.

### ISSUE THREAD

**Issue by DavidSpivey** [philsinatra/NestedCommentsVSCode#50]
I have my css embedded in a <style> tag in an HTML file. I prefer in some circumstances not to export the css to an external .css file. Unfortunately, this extension does not recognize css in an HTML file. Commenting css adds html  comment tags, which causes a syntax error, and breaks the css. I imagine this same issue exists for compiled HTML such as php with a <style> tag.

**Comment by philsinatra** [comment]
Done. Version 4.1.0 published with support for embedded language detection.

**Comment by DavidSpivey** [comment]
Thank you for the swift resolution!
