### ISSUE TITLE
Excessive space after uncommenting

### ISSUE THREAD

**Issue by john-cj** [philsinatra/NestedCommentsVSCode#7]
A small, but annoying bug. After uncommenting, there appears one excessive space. In my example, you can see it before class name on the line 9:

![nested](https://user-images.githubusercontent.com/18004961/39360929-dd241f78-4a28-11e8-8c7c-44c5cf8d8e7f.JPG)

**Comment by philsinatra** [comment]
I pushed an update [2.1.2] that addresses the extra space. Thanks for spotting this.
