### ISSUE TITLE
alt+cmd+/ css missing space

### ISSUE THREAD

**Issue by id77** [philsinatra/NestedCommentsVSCode#8]
**issue：**
`alt+cmd+/` css missing space

Nesting again will be wrong
```
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    /*box-sizing: border-box;*/
}
```
====>
![image](https://user-images.githubusercontent.com/9592236/42981215-a862b4bc-8c0d-11e8-8d19-7c79a39d2fcf.png)

Good
```
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    /* box-sizing: border-box; */
}
```
====>
![image](https://user-images.githubusercontent.com/9592236/42981513-067ea1d6-8c0f-11e8-9cc8-6a033a49d1c6.png)

**Improve：**
The line where the cursor is, press `alt+cmd+/` to directly comment the entire line

![image](https://user-images.githubusercontent.com/9592236/42981343-3e0070ea-8c0e-11e8-9293-97015551e3ca.png)
====>
```
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;/**/
}
```
expect：
```
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    /* box-sizing: border-box; */
}
```

**Comment by philsinatra** [comment]
The spacing issue mentioned outlined at the beginning of your issue has been addressed with version 2.1.4.

The improvement you describe duplicates built in functionality. You can automatically comment the current line based on cursor position using the default <kbd>cmd</kbd><kbd>/</kbd> shortcut.
