### ISSUE TITLE
Comment markers placement

### ISSUE THREAD

**Issue by joelgenter** [philsinatra/NestedCommentsVSCode#9]
When you select multiple at beginning and end of instead of line beginnings and ends

The comment markers are inserted into at the beginning and end of the selected text rather than the beginning and end of the lines that are selected. This manifests itself when you have two partially selected lines as shown below.
![image](https://user-images.githubusercontent.com/14948437/46048013-2754b100-c0dc-11e8-82df-99c39ce4680f.png)

When I use the plugin hotkeys to comment these lines, the comment markers are inserted at the beginning and end of the selection as shown below.
![image](https://user-images.githubusercontent.com/14948437/46048063-67b42f00-c0dc-11e8-904c-9179b2e9b32a.png)

I assume the desired behavior is for the comment markers to be inserted at the beginning and end of lines that are selected rather than the beginning and end of the selection itself. This is how VS Code's built-in comment feature behaves as shown below.
![image](https://user-images.githubusercontent.com/14948437/46048117-aba73400-c0dc-11e8-83ff-ad95c7a6b511.png)
Becomes
![image](https://user-images.githubusercontent.com/14948437/46048132-be216d80-c0dc-11e8-8ccd-7960c1967ded.png)

I can obviously work around this but it'd be really if it behaved consistently with VS Code's built-in comment feature. Great tool! 😊

**Comment by philsinatra** [comment]
Hi @joelgenter. The intended desire is actually to have the comment markers inserted based on the selection, not the entire line. This stems originally from the consideration that not everyone uses the same formatting settings for their code and in some cases there could be multiple elements on the same line. In those cases, it may not be ideal to have the entire line commented out since the user may only want to comment out certain elements nested in other elements that technically appear on the same line.

**Comment by joelgenter** [comment]
Noted. That's understandable. Maybe a configuration option for this behavior would be a good move down the road. There are two oft-occurring cases in which it saves time to comment the whole line:

1. When the cursor is sitting on the line of interest without anything selected and you hit the comment hot-keys to quickly comment out that line.
2. When you want to comment out a block of code and use Shift-Up/Down (to highlight a part of the above/below line(s)) followed by the comment hot-keys to quickly comment out the lines that are partially selected.

But there seems to be a slightly different issue. If multiple lines are highlighted and the selection ends part-way through a line, commenting will remove part of the line beginning at the end of the selection.
![image](https://user-images.githubusercontent.com/14948437/46166303-bfbb7480-c247-11e8-891c-72acc17d4cb6.png)
Becomes:
![image](https://user-images.githubusercontent.com/14948437/46166343-d8c42580-c247-11e8-97d7-171bed784ddb.png)

**Comment by philsinatra** [comment]
I'll make a note to consider configuration options during the next update. Maybe two different keyboard shortcuts, one for selection based and one for full line based commenting. Would that be better than a global preference attached to a single keyboard shortcut?

**Comment by joelgenter** [comment]
Good question. There could be two configuration options, one for setting the hotkeys for the current behavior and another for setting the hotkeys for the behavior that's consistent with VS Code's commenting feature. That would give the user control over which behavior(s) to use and how to them.

**Comment by philsinatra** [comment]
Okay, I'll make a note and consider this in the next update. Thanks for your feedback.

**Comment by joelgenter** [comment]
Should I open a new issue for the tag-removal behavior that I outlined?

**Comment by philsinatra** [comment]
No I made notes and have this conversation. Should be good to go. Thanks.

**Comment by bernatfortet** [comment]
I'd also love to have this configuration option:
Here's a video of the issue: https://streamable.com/vbko5
